### ISSUE TITLE
CORS issue in Unleash proxy for accessing  from browser.

### ISSUE THREAD

**Issue by sandeepbhatkande** [Unleash/unleash-client-node#192]
I am using Unleash proxy for accessing unleash server from browser (React project). I have started Unleash server in docker container. While using it is giving CORS problem beacuse both server are in different origin. please suggest how to set headers to unleash server in docker container. 

_Originally posted by @sandeepbhatkande in https://github.com/Unleash/unleash-client-node/issue_comments/708144670_

**Comment by ivarconr** [comment]
Hi @sandeepbhatkande,

can you please explain what you mean by using the "unleash-proxy"? Do you mean the official [Unleash-proxy](https://www.unleash-hosted.com/articles/the-unleash-proxy) part of the "enterprise" offering? In that case the cors headers should be solved for you. You should not need cors headers on Unleash server itself as the clients connect to the proxy.

**Comment by sandeepbhatkande** [comment]
Hi @ivarconr ,

Thanx for quick response. Just I will explain what I want to do. I am using 2 micro-services one for Front-End (node server with react) and second one for Back-End(spring boot ). Now I wanted to implement unleash for toggle based development. On backend side I have successfully implemented with [unleash-client-java](https://github.com/Unleash/unleash-client-java). Now My Front-End is running on browser hence I am not able to use [unleash-client-node](https://github.com/Unleash/unleash-client-node) directly. I found your answer [Unleash for a frontend client ( react )](https://github.com/Unleash/unleash/issues/414)  and try to implement [unleash-proxy-client-js](https://github.com/unleash-hosted/unleash-proxy-client-js). Then I am getting CORS issue.

Please suggest me best approach to implement Unleash eaither I have to initialize on backend and then bring all toggle features to frontend via http call or initailize Unleash SDK to backend as well as frontend seperately

**Comment by ivarconr** [comment]
generally we do not recommend exposing unleash-server directly to the frontend, as it will possibly expose all the configuration to everyone. If you want to do it, and it makes sense for your use-case, you need to use the npm distribution and register a [preHook](https://unleash.github.io/docs/getting_started#2-or-programmatically) to set proper CORS headers. The general advice is to evaluate toggles for a specific user serverside, and only expose the evaluated result to the user. 

The unleash-proxy-js will only work with the official Unleash-proxy. We are considering to open-source the proxy at some point, but no promises yet.

**Comment by sandeepbhatkande** [comment]
Hi @ivarconr ,

Thanx for your help. I have developed as per your recommended method that exposing unleash-server directly to the frontend. I am evaluating user specific toggles on server side and loading it to frontend at time of load application or refresh application. Now I just worried about inconsistancy between backend and frontend toggles. backends toggles are refreshing after some time interval but at same time frontend toggles are not refreshing unless someone making reload to application. please suggest way to synch backend and frontend toggles. Thank you.

**Comment by sandeepbhatkande** [comment]
@ivarconr , please comment on my above query.

**Comment by ivarconr** [comment]
> worried about inconsistancy between backend and frontend toggles. backends toggles are refreshing after some time interval but at same time frontend toggles are not refreshing unless someone making reload to application.

First: So its hard to give a correct answer to your question, because it depends on your context. First I would encourage your to note use the same feature toggles in frontend and backend. Also, in many scenarios, it will be enough to hide the new functionality in the UI, and the backend can handle both the old version and the new version. 

Second: you can do polling for updates in the frontend as well. But do you really want to change the UI for the user in the middle of a session? What if it changes the check-out flow? It could be confusing for the user. But this really depend on your context. 

third: The really hard part is if you do server-side rendering and dehydrate in the browser. Then you must make sure toggles does not change, as this will make your UI flicker, if something suddenly is changed. 

I love to engage in longer discussions on this, preferably [on slack](https://join.slack.com/t/unleash-community/shared_invite/enQtNjUxMjU2MDc0MTAxLTJjYmViYjkwYmE0ODVlNmY1YjcwZGRmZWU5MTU1YTQ1Nzg5ZWQ2YzBlY2U1MjlmZDg5ZDRmZTMzNmQ5YmEyOGE)
