### ISSUE TITLE
Unleash event emission not reliable

### ISSUE THREAD

**Issue by Rob-Read** [Unleash/unleash-client-node#199]
This was a major headache for me to deal with over the past day. There is no guarantee that we can reliably hook into the ready event since the emission of the ready event from storage -> repository -> unleash can occur before the unleash constructor has finished creating the instance, resulting in the ready event firing before we have the chance to provide a hook. 

```
let instance = initialize({...}) <--- ready event can fire during construction
instance.on('ready', () => foo()) <---- not possible to then use it as a hook, as it's already fired before we've defined our hook
```

This was a major headache because we use the client within our web app and we're hooking into the ready event to start our web-app. Because of the race condition mentioned above, deploying this change could cause our app start-up to never be executed.

**Comment by ivarconr** [comment]
Thanks for reporting, you are absolutely right. 

When emitting from a constructor we should make sure to wrap the emitting code inside a `process.nextTick()`, in order to make sure the clients are able to subscribe for that event. 

I believe changing https://github.com/Unleash/unleash-client-node/blob/master/src/unleash.ts#L124 to something like this should solve your scenario:

```js
process.nextTick(() => this.emit('ready'))
```

I am a bit puzzled to never have experienced this myself, but it might be affected by how fast the repository is able the read the backup on file.
