### ISSUE TITLE
A worker process has failed to exit gracefully and has been force exited.

### ISSUE THREAD

**Issue by nploi** [Unleash/unleash-client-node#302]
Hello everybody, i have a problem when i write unit-test for my project.

Description:
I have a simple unit-test.

```typescript
import nock from 'nock';
import { startUnleash } from 'unleash-client';

describe('test-unleash', () => {
    const url = 'http://test.app/';
    beforeEach(() => {
        nock(url).get('/client/features').reply(200, { features: [] });
    });

    it('test unleash', async () => {
        const unleash = await startUnleash({
            appName: 'app-test',
            url: url,
            disableMetrics: true,
        });
        expect(unleash.isEnabled('feature_a')).toEqual(false);
    });
});

```
but after i run above unit-test  with command `npx jest --testNamePattern='test-unleash'`,  i see 
```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. 
Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
```
any idea for fix this one. 
Thank you.

**Comment by ivarconr** [comment]
Hi, to stop internal background processes you should destroy unleash after it completes. 

`unleash.destroy();`

For unit tests I would personally consider mocking unleash, instead of creating an actual instance. 

Another approach would be to disable "fetching" and "metrics" and boostrap the Unleash SDK with a defined feature toggle configuration.

**Comment by nploi** [comment]
Hi @ivarconr, 
i use `unleash.destroy();` and i work for me.
thank you!
