### ISSUE TITLE
Question: Can this be used in a browser?

### ISSUE THREAD

**Issue by yukw777** [Unleash/unleash-client-node#62]
Hello everyone. I'm trying to use unleash to control my frontend application. I do understand that this client was originally written to be used for a node server application, and currently if I try to use it in a browser, it throws an error. (fs module is not found). Looks like the node client uses `fs` to store features it fetched from the unleash backend server. I'm wondering if there's a way to switch out the storage in the client so it uses the browser local storage. Thanks in advance!

**Comment by ivarconr** [comment]
> Can this be used in a browser? 
The short answer is no.

You will typically not expose the _unleash-api_ directly to the browser because the toggle configurations include all your toggles and may contain user-sensitive data such as userIds, emails etc (who to enable for).

The recommended approach is to set up a small proxy-service for the browser, where the browser can request whether a list of toggles should be on/off for the specific user (extra bonus is to store this in local-storage, and sync regularly). In the proxy-service it would us this node-client to make the implementation super simple.

**Comment by yukw777** [comment]
Thanks @ivarconr! What you suggested is what I was gonna do, but I thought I'd ask anyway. I'll close the issue.

**Comment by xp500** [comment]
Hi @ivarconr, I have a follow up question related to this. Is it possible to get the full list of toggles using this client? I'd like my proxy service to answer with the whole list of toggles instead of just a subset for a given user. I couldn't find if/where this library exposes the full list of active toggles.

Thanks!

**Comment by elhoyos** [comment]
I'm stepping in here.

@xp500, I did something regarding your question [here](https://github.com/Unleash/unleash-client-node/compare/master...elhoyos:static-features). Those are part of a way to configure unleash client via [static files](https://github.com/Unleash/unleash-client-node/issues/74). I'm planning to integrate these here in the near future but feel free to use, tweak, cherry-pick or PR.

**Comment by ivarconr** [comment]
https://docs.getunleash.io/sdks/unleash-proxy
