### ISSUE TITLE
Feature reference in variant

### ISSUE THREAD

**Issue by elhoyos** [Unleash/unleash-client-node#78]
As stated in https://github.com/Unleash/unleash/pull/297#issuecomment-361762027 I'm trying to integrate Google Optimize with unleash and at some point I have a special version of feature set that serves well for this purpose:

```js
{
  version: '2.special', // v2 from unleash + optimize experiment id
  features: [{
    name: 'laugh',
    enabled: true,
    description: 'Experiment a new world surrounded by laugh',
    goExperimentId: 'HXEMMfooUiQQ6zMKDI4guivw',
    strategies: [...],
    variants: [...],
  }, ...
}
```

And later in the pipeline I need access to the `goExperimentId` value in order to signal Google Optimize about the experiment to be using.

Right now, I'm sorts of doing the following:

```js
const feature = conf.unleashFeatures.features.find(f => f.name === featureName);
ga.signalExperiment(feature.goExperimentId, variant.id);
```

However I find the lookup step kind of unnecessary. Do you see any negative consequence on referencing the `Feature` from within a `Variant`?

```js
ga.signalExperiment(variant.feature.goExperimentId, variant.id);
```

**Comment by ivarconr** [comment]
On top of my head I see no big problems with this; The feature-toggle definitions cumming from the server should be treated as immutable objects in the client anyways. 

However, it could be that the experiment definition should be should be treated as a separate concern, with support for custom experiment configurations. Then all variants could have the base-configuration from the "experiment" lever, but they are also overridable per variant. 

```js
{
  version: '2',
  features: [{
    name: 'laugh',
    enabled: true,
    description: 'Experiment a new world surrounded by laugh',
    strategies: [...],
    experiement: {
       configuration: { 
          experimentId: "123",
          color: "silver"
       },
       variants: [
          {
             name: "control"
          },
          {
             name: "blue",
             configuration: {
               color: "blue"
             }
          }
       ],
    }
  }], ...
}
```

Another way to solve this would be to resolve all the variant specific configuration on the server side, so that all variants have the correct configuration. This would possibly increase the payload some, but ease the client implementation.
